[package]
name = "ip-over-airtag"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
hex = "0.4.3"
offline-finding = { path = "../../airtag/needle/offline_finding", features = [
] }
p224 = "0.13.2"
rand = "0.8.5"
sha2 = "0.10.8"
