[package]
name = "ip-over-airtag"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
base64 = "0.22.1"
hex = "0.4.3"
offline-finding = { path = "../../airtag/offline-finding", default-features = false, features = [
] }
p224 = "0.13.2"
rand = "0.8.5"
sha2 = "0.10.8"
